"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var constants_1 = require("./constants");
exports.PREFIX = constants_1.PREFIX;
exports.SET_LANG = constants_1.SET_LANG;
exports.SET_MESSAGES = constants_1.SET_MESSAGES;
var TranslationContext_1 = require("./context/TranslationContext");
exports.TranslationContext = TranslationContext_1.default;
var Translator_1 = require("./components/Translator");
var get_1 = require("./helpers/get");
exports.get = get_1.default;
var useAvailableLanguagesSelector_1 = require("./hooks/useAvailableLanguagesSelector");
exports.useAvailableLanguagesSelector = useAvailableLanguagesSelector_1.default;
var useCurrentLanguageSelector_1 = require("./hooks/useCurrentLanguageSelector");
exports.useCurrentLanguageSelector = useCurrentLanguageSelector_1.default;
var useTranslationReducer_1 = require("./hooks/useTranslationReducer");
exports.useTranslationReducer = useTranslationReducer_1.default;
var useTranslationSelector_1 = require("./hooks/useTranslationSelector");
exports.useTranslationSelector = useTranslationSelector_1.default;
exports.default = Translator_1.default;
